### PR TITLE
docs(coc): update to match main fastify repo

### PR DESCRIPTION
**Pull request by Fdawgs**
#### Checklist

- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by Uzlopak — APPROVED** [review]
Did we ever added ourselfs to the peanut gallery?

**Comment by Fdawgs** [comment]
> Did we ever added ourselfs to the peanut gallery?

The what now?

**Comment by Uzlopak** [comment]
https://github.com/EthicalSource/contributor_covenant/issues/636

**Comment by Fdawgs** [comment]
> [EthicalSource/contributor_covenant#636](https://github.com/EthicalSource/contributor_covenant/issues/636)
> 
> I think there is a page where you can add your product/organization as users of the coc.

OpenJS Foundation is listed, so I guess we're covered under that.

**Pull request merged**
