### PR TITLE
chore(issue_template): replace remaining `md` issue forms with yaml configured issue forms

### PR DESCRIPTION
**Pull request by Fdawgs**
Saw that YAML issue forms are now in [public beta](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/) and was reminded that the rest of the forms also need migrating.

The new forms attempt to retain as much of the format/content of the original markdown forms.

#### Checklist

- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — COMMENTED** [review]
I think we should leave one of the template as "free form".

**Comment by Fdawgs** [comment]
> 
> 
> I think we should leave one of the template as "free form".

Any preference as to which one?

**Comment by mcollina** [comment]
Maybe just add another template like "none of the above"?

**Comment by jsumners** [comment]
FYI: These templates don't make much sense on the `website` repo.

**Comment by Fdawgs** [comment]
> 
> 
> FYI: These templates don't make much sense on the `website` repo.

Good point, thanks @jsumners. We will need to create separate forms in the `website` repo.
If the `website` repo has its own `.github/ISSUE_TEMPLATE` directory then it won't inherit these files, as [noted in the community health file documentation](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file#about-default-community-health-files).

**Comment by Fdawgs** [comment]
> 
> 
> Maybe just add another template like "none of the above"?

Cool beans, have create an `other` form that has the prerequisite checks and then a free form textarea.

**Review by mcollina — APPROVED** [review]
lgtm

**Review by jsumners — APPROVED** [review]

**Pull request merged**
